name: CI (API + Web + ThemeBuilder guard)

on:
  push:
    branches: [ main, develop, alpha, beta, rtm ]
  pull_request:

permissions:
  contents: read
  security-events: write
  actions: read
  packages: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: "20"
  DOTNET_VERSION: "8.0.x"
  WEB_DIR: web
  API_DIR: api
  THEME_PACKAGE_NAME: mcpx-kendobridge
  THEME_PACKAGE_DIR: design/themebuilder/export/mcpx-kendobridge

jobs:
  theme-guard:
    name: ThemeBuilder export checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq (for JSON checks)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Verify ThemeBuilder export is committed
        shell: bash
        run: |
          set -euo pipefail
          PKG="$THEME_PACKAGE_DIR/package.json"
          CSS="$THEME_PACKAGE_DIR/dist/css/${THEME_PACKAGE_NAME}.css"
          SCSS_DIR="$THEME_PACKAGE_DIR/dist/scss"

          echo "Checking ThemeBuilder package at: $THEME_PACKAGE_DIR"
          test -f "$PKG"      || { echo "::error file=$PKG::Missing ThemeBuilder package.json"; exit 1; }
