name: Validate ThemeBuilder vendor

on:
  push:
    paths:
      - 'design/themebuilder/**'
      - '.github/workflows/validate-themebuilder.yml'
  pull_request:
    paths:
      - 'design/themebuilder/**'
      - '.github/workflows/validate-themebuilder.yml'
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-themebuilder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify vendored ThemeBuilder packages
        shell: bash
        run: |
          set -euo pipefail

          root="design/themebuilder/export"
          if [[ ! -d "$root" ]]; then
            echo "::notice title=ThemeBuilder::No $root/ directory; nothing to validate."
            exit 0
          fi

          echo "Scanning $root for packages…"
          found_any=false
          failed_any=false

          shopt -s nullglob
          for pkg in "$root"/*; do
            [[ -d "$pkg" ]] || continue
            found_any=true

            echo "— Checking package: $pkg"
            pkg_json="$pkg/package.json"
            dist_dir="$pkg/dist"

            # 1) Must have package.json
            if [[ ! -f "$pkg_json" ]]; then
              echo "::error file=$pkg::Missing package.json"
              failed_any=true
            fi

            # 2) Must have non-empty dist/
            if [[ ! -d "$dist_dir" ]]; then
              echo "::error file=$pkg::Missing dist/ directory"
              failed_any=true
            else
              if ! find "$dist_dir" -type f -print -quit | grep -q .; then
                echo "::error file=$dist_dir::dist/ is empty"
                failed_any=true
              fi

              # 3) dist/ files must be tracked in git
              if ! git ls-files -- "$dist_dir" | grep -q .; then
                cat <<'EOF'
::error::No files under dist/ are tracked by git.
Tips:
- Ensure your .gitignore has this exception AFTER any 'dist/' rule:
    !design/themebuilder/export/**/dist/**
- Re-add & commit:
    git add -f '"$dist_dir"'
    git commit -m "Vendor ThemeBuilder dist"
EOF
                failed_any=true
              fi

              # 4) Guard against >100MB files (GitHub hard limit)
              if find "$dist_dir" -type f -size +95M -print -quit | grep -q .; then
                cat <<'EOF'
::error::One or more files in dist/ exceed ~95MB.
Use Git LFS or reduce bundle size:
  git lfs install
  git lfs track "design/themebuilder/export/**/dist/**"
  git add .gitattributes && git commit -m "Track ThemeBuilder dist with LFS"
EOF
                failed_any=true
              fi
            fi
          done

          if ! $found_any; then
            echo "::warning title=ThemeBuilder::No packages found under $root/. If this is expected, ignore this check."
          fi

          # 5) (Advisory) Suggest .gitignore exception if needed
          if grep -Eq '^[[:space:]]*dist/' .gitignore 2>/dev/null; then
            if ! grep -Fq '!design/themebuilder/export/**/dist/**' .gitignore; then
              echo "::warning file=.gitignore::You ignore 'dist/' but don't have the exception '!design/themebuilder/export/**/dist/**'. Consider adding it."
            fi
          fi

          if $failed_any; then
            echo "ThemeBuilder vendor validation failed."
            exit 1
          fi

          echo "ThemeBuilder vendor validation passed ✅"
