name: Validate ThemeBuilder vendor

on:
  push:
    paths:
      - 'design/themebuilder/**'
      - '.github/workflows/validate-themebuilder.yml'
      - 'scripts/validate-themebuilder.sh'
  pull_request:
    paths:
      - 'design/themebuilder/**'
      - '.github/workflows/validate-themebuilder.yml'
      - 'scripts/validate-themebuilder.sh'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Convert CRLF -> LF in CI in case the script was committed with Windows endings
      - name: Ensure LF line endings for script
        run: |
          if grep -q $'\r' scripts/validate-themebuilder.sh; then
            echo "::warning::Converting CRLF to LF in scripts/validate-themebuilder.sh"
            sed -i 's/\r$//' scripts/validate-themebuilder.sh
          fi

      - name: Make script executable
        run: chmod +x scripts/validate-themebuilder.sh

      - name: Bash syntax check
        run: bash -n scripts/validate-themebuilder.sh

      - name: Validate vendored ThemeBuilder packages
        run: ./scripts/validate-themebuilder.sh
